version: '3.8'
services:
  mysql_srv:
    image: mysql:8.0
    container_name: mysql
    stdin_open: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: ${HOST_PORT_MYSQL}
    ports:
      - "${HOST_PORT_MYSQL}:3306"
    volumes:
      - database-volume:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs

  backend_srv:
    build: 
      context: ./backend
    depends_on:
      - mysql_srv
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_HOST: ${DATABASE_HOST}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      PORT: ${HOST_PORT_BACKEND}
    ports:
      - "${HOST_PORT_BACKEND}:8081"
    volumes:
      - ./backend:/backend
    command: tail -f /dev/null #used for debugging

  frontend_srv:
    build: 
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    environment:
      PORT: ${HOST_PORT_FRONTEND}
    ports:
      - "${HOST_PORT_FRONTEND}:80"

    volumes:
      - ./frontend:/frontend
  
  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PORT: ${HOST_PORT_PHPMYADMIN}
    ports:
      - "${HOST_PORT_PHPMYADMIN}:80"

volumes:
  database-volume: