services:
  mysql_srv:
    image: mysql:8.0
    container_name: mysql
    stdin_open: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: ${HOST_PORT_MYSQL}
    ports:
      - "${HOST_PORT_MYSQL}:3306"
    volumes:
      - database-volume:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
    networks:
      - ekonomiapp-network

  backend_srv:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql_srv
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_HOST: ${DATABASE_HOST}
      HOST_PORT_FRONTEND: ${HOST_PORT_FRONTEND}
      VITE_HOST_PORT_BACKEND: ${VITE_HOST_PORT_BACKEND}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      PORT: ${VITE_HOST_PORT_BACKEND}
    ports:
      - "${VITE_HOST_PORT_BACKEND}:8081"
    networks:
      - ekonomiapp-network

  frontend_srv:
    build: 
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_AXIOS_BASE_URL=${VITE_AXIOS_BASE_URL}
        - VITE_HOST_PORT_BACKEND=${VITE_HOST_PORT_BACKEND}
    environment:
      PORT: ${HOST_PORT_FRONTEND}
    ports:
      - "${HOST_PORT_FRONTEND}:80"
    volumes:
      - ./frontend:/frontend
    networks:
      - ekonomiapp-network
  
  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PORT: ${HOST_PORT_PHPMYADMIN}
    ports:
      - "${HOST_PORT_PHPMYADMIN}:80"
    networks:
      - ekonomiapp-network

volumes:
  database-volume:

networks:
  ekonomiapp-network: